# Generated by Django 2.1.4 on 2018-12-20 00:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon'),
        ),
    ]
